### ISSUE TITLE
!wmakesource crashes on live target

### ISSUE THREAD

**Issue by Alois-xx** [rodneyviana/netext#15]
**To Reproduce**
1. Start a simple e.g. WPF Hello World App
2. Attach Windbg
3. Load Netext (latest 2.1.57.5000\x64)
4. Do !wk to get some stack frames
5. Try to decmpile with !wmakesource

**Expected behavior**
Decompiled code

** Actual Behavior **
windbg: 38 exceptions
windbg (18600): 36 exceptions
	Attempted to read or write protected memory. This is often an indication that other memory is corrupt.:   Attempted to read or write protected memory. This is often an indication that other memory is corrupt.: 2 exceptions
		dynamicClass.IL_STUB_CLRtoCOM(unsigned int64,value class Microsoft.Diagnostics.Runtime.Interop.MEMORY_BASIC_INFORMATION64&)
			NetExt.Shim.DebugApi.AddressType(unsigned int64)
			NetExt.Shim.DebugApi.ReadMemory(unsigned int64,!!0&,bool)
			NetExt.Shim.Module.get_DOSHeader()
			NetExt.Shim.Module.get_FileImageType()
			NetExt.Shim.Module.get_CorHeader()
			NetExt.Shim.Module.get_IsClr()
			NetExt.Shim.MDTarget.MakeSourceInternal(unsigned int64)
			dynamicClass.IL_STUB_COMtoCLR(int64)
			

**Desktop (please complete the following information):**
 - OS: Win 10 1803

**Comment by rodneyviana** [comment]
Some considerations in general until I test your scenario:
You have to be at a frame that is managed and it is not always possible in mixed stacks. To be sure you get the right address. For instance, get a !wclrstack or !clrstack and get the IP address that you want to decompile and do !wmakesource <address>. See if it still fails. Notice that the .NET libraries are not good candidates to decompile as they are huge files.

Doing the repro:
I will follow your steps to see if I can repro.

**Comment by rodneyviana** [comment]
I was able to reproduce in live targets. I am investigating and will let you know.

**Comment by rodneyviana** [comment]
Alois-xx,

Would you be able to test the new version to see if it resolved the problem with !wmakesource?

Thanks,

Rodney

**Comment by Alois-xx** [comment]
Sure! I will take a look.

**Comment by Alois-xx** [comment]
The exceptions are no longer happening. This seems to work better than before although there are still cases were it does not work. 
Thanks for the great extension. This one is immensely helpful especially when some Postsharp stuff has ruined the code!
