### ISSUE TITLE
In command !wservice, property Is Throttled? is always true

### ISSUE THREAD

**Issue by JPGRodrigues** [rodneyviana/netext#3]
Just collected a dump on a WCF process hosted in IIS.
Whenever I run the command !wservice <address> the Is Throttled property is always true
 (even if the service was just started and I only one service call was performed)

!wservice 0000024250957ee0

Service Info
================================
Address            : 0000024250957EE0
Configuration Name : WCFApplicationWithMultipleBindings.Service1
State              : Opened
EndPoints          : 0n2
Base Addresses     : 0n3
Behaviors          : 0n10
Runtime Type       : WCFApplicationWithMultipleBindings.Service1
Is Throttled?      : True
Calls/Max Calls    : 0n0/0n64
Sessions/Max       : 0n0/0n400
Events Raised      : No Event raised
Handles Called     : OnOpeningHandle OnOpenedHandle 
Session Mode       : False
Extensions         : 00000242509bc390

**Comment by rodneyviana** [comment]
You may create a service without throttling. Throttling is a service behavior.

**Comment by JPGRodrigues** [comment]
Hello Rodney,

My understanding of the property was that it would tell if the service was in throttling situation :D

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 17134 - 16.0.10228.20104]

________________________________

**Comment by rodneyviana** [comment]
Probably my naming was not the best :)
