### ISSUE TITLE
!wstack dumps not all stack objects like !dso

### ISSUE THREAD

**Issue by Alois-xx** [rodneyviana/netext#5]
I love the !wstack command but for some cases where I am searching for stale references of already left methods I sometimes want to see if some hints of already left methods are on the stack. 

The !dso command travereses the full stack but !wstack only the valid one. 
Could you add to !wstack e.g. a -full option to list all managed references? 

By the way your Windbg extension is by far the best out there for managed code.

**Comment by rodneyviana** [comment]
Hi Alois-xx,

Do you mean show repeats? !wstack traverses the full stack, covering even more range than !sos.dso. Do you have a particular repro you can share?

Thanks,

Rodney

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Alois-xx** [comment]
I will check with a specific dump. I have seen that !wstack returned no objects but !dso did return some objects of a threadpool thread which was waiting for more work wich was before that juggling around some Window objects which did cause some deadlock. With !wstack I did not get any objects back. It looks like !wstack is looking only at the stack from top to the currently executing method but not below of "older" methods which are no longer on the stack.
