### ISSUE TITLE
Does !wfrom support nesting?

### ISSUE THREAD

**Issue by freaksterrao** [rodneyviana/netext#7]
Does !wfrom support nesting? I could not find an example for the same.

I have a dictionary from which I am trying to read the entries and recover the address of value.
!wfrom returns an array. But I am unable to pipe it to another !wfrom to further process it.

example of what I want to do:
!wfrom -array (!wfrom -nofield -nospace -array 181f6c24 select value) select somefield
181f6c24 is the address of entries field of a dictionary.

**Comment by rodneyviana** [comment]
It does not support nesting. The work-around would be to use WinDbg command ".for". In the example below I print the parameters of a SQL command using this technique:
```
.foreach ({$addr} {!wfrom -type *.sqlcommand -nospace -nofield where (_commandType == 4) select _parameters._items._items}) { r @$t1= {$addr} ;!wfrom -type *.sqlcommand -nofield -nospace where (_parameters._items._items==$dbgeval("@$t1")) "\n", _commandText," [",$addr(),"]\n========================"; !wfrom -nospace -nofield -array {$addr}  _parameterName,"=",$pp(_value) }

dbo.proc_getSiteIdOfHostHeaderSite [00000001011FCD90]
========================
@RETURN_VALUE=0n0
@HostHeader=sp.contoso.com
@RequestGuid={00000000-0000-0000-0000-000000000000}
```

For your case it would be something like:
```
.foreach ({$addr} {!wfrom -nofield -nospace -array 181f6c24 select value}) { !wfrom -obj {$addr} select somefield; } 
```
```

```

**Comment by freaksterrao** [comment]
Thanks Rodney that worked for me.
