### ISSUE TITLE
[XmlParsing] Attributes with empty values seem not to get empty value restored.

### ISSUE THREAD

**Issue by mitikov** [rodneyviana/netext#9]
First of all - a huuuge thanks for the extension, it saves the day!

I'm using `!wxml` command with source xml like:

    <dataviews>
      <dataview name="FilterDataView" assembly="Sitecore.Kernel" type="Sitecore.Web.UI.HtmlControls.FilterDataView" Parameters="" />
    </dataviews>

While the restored version does not get an empty value for parameters:

  <dataviews>
    <dataview name="FilterDataView" assembly="Sitecore.Kernel" type="Sitecore.Web.UI.HtmlControls.FilterDataView" Parameters />
  </dataviews>

As a result, the attribute without value breaks further parsing =\

I'm eager to contribute if you could hint me where to look at.

Thanks.

**Comment by rodneyviana** [comment]
Hi mitikov,

Thanks for bringing this up. The new version 2.1.50.5000 now available resolved the issue. If you are curious to see what was wrong you can compare the changes in source code for this new version. Please close the issue if this resolved your issue.

Thanks,

Rodney

**Comment by mitikov** [comment]
Thanks for prompt reply, I'll try out.
P.s. Just [blogged](https://making-it-faster.blog/2019/11/21/windbg-commands-configuration/) about your extension :)

**Comment by rodneyviana** [comment]
Nice. You should also try !wdo and !wselect * from ..

**Comment by mitikov** [comment]
@rodneyviana A new version clrMD is to be baked, you might want to share your thoughts: https://github.com/microsoft/clrmd/issues/311
